### ISSUE TITLE
World Cup 2018

### ISSUE THREAD

**Issue by emirb** [emir/euro2016#1]
Greetings namesake! :-)

Just adding an issue here, in time before World Cup.

Competition endpoint is already available: http://api.football-data.org/v1/competitions/467, so I'd propose a fork as `worldcup2018` or something. The basic functionality would be the same.

**Comment by emir** [comment]
Hello namesake! :)

Here it is: [worldcup2018](https://github.com/emir/worldcup2018)

**Comment by emirb** [comment]
Thx! Have a nice day :)
